### ISSUE TITLE
Multiple inreach Devices

### ISSUE THREAD

**Issue by ericbrown** [kemenril/iR-APRSISD#1]
I ran across this on reddit. Thanks for it (and for sharing it).

I'm the user that said he had multiple devices.  I am going to test them both out this weekend.  I can provide the KML file to you if you'd like to see it - and then maybe we can tweak this to be able to handle multiple IMEI's in a KML file / mapshare url?

**Comment by ericbrown** [comment]
Multiple inReach device support added in https://github.com/kemenril/iR-APRSISD/pull/2

**Comment by kemenril** [comment]
Decided to try a somewhat different tactic than you were using.  Take a look at the new code, and let me know if it seems to behave in the correct way.  Pay special attention to the new Devices section in the config file, which you can define for a fixed multi-device mapping, or leave undefined.  If you leave it undefined, the first device that it finds gets your SSID as defined, and the number is incremented for each subsequent device.

There is also a command-line option now that allows you to specify an IMEI, but that option overrides the entire Device section, forcing a static map containing only that IMEI with the default SSID.  Additionally, a -C option has been added to allow you to run with an alternate configuration file, in case you want something like a different APRS symbol for each device, for example, which isn't currently supported in another way. 

Anyway, it's still mostly speculative, but take a look, and let me know if it helps.

**Comment by ericbrown** [comment]
I do like your approach...its a bit cleaner.

I'm going to test this out over the next few days with my 2 devices and let you know.

**Comment by ericbrown** [comment]
The new approach works really well. I'd say this issue is closed. I really like the latest code too.

**Comment by kemenril** [comment]
Thanks,
 I had been wondering whether you'd seen it after the big refactor the other day.  I'm much happier with it since then, it should be close enough to functionally identical, and the new structure is such that if I want to add, say, support for Spot tracking devices or other slightly different data sources, it should be relatively simple.  Of course, I don't have, nor do I know anyone with, a Spot, either, so it may need to wait. :)
