### ISSUE TITLE
Script fails in the middle of running. Operating in Georgia.

### ISSUE THREAD

**Issue by evgeny-mezin-epam** [kemenril/iR-APRSISD#4]
`----------------Packet Forwarding Summary----------------
|       2021-07-29 07:43
| SSID          DevID                   Packets forwarded
| EW1EM-12              0
---------------------------------------------------------

----------------Packet Forwarding Summary----------------
|       2021-07-29 07:48
| SSID          DevID                   Packets forwarded
| EW1EM-12              0
---------------------------------------------------------

Traceback (most recent call last):
  File "./ir-aprsisd", line 365, in <module>
    for packet in getEvents():
  File "./ir-aprsisd", line 269, in getEvents
    res = parsePlacemark(PM)
  File "./ir-aprsisd", line 235, in parsePlacemark
    elevation       = float(elevation) * 3.2808399
ValueError: could not convert string to float: '-1.00 m from MSL'`

**Comment by evgeny-mezin-epam** [comment]
is it related to Altitude conversion ?
Close to the sea shore that value could be negative. For me it's around -18m

**Comment by evgeny-mezin-epam** [comment]
Data Sample is the following
`<Data name="Elevation">
      <value>-54.35 m from MSL</value>
  </Data>
`

Looks like it doesn't match the RegExp used in string 234
https://github.com/kemenril/iR-APRSISD/blob/299cea7aff5007c50e79daf981a3ba0ac648b55f/ir-aprsisd#L234
so, i am gonna try this one instead
`^(-?\d+\.?\d+)\s*m.*`

**Comment by kemenril** [comment]
Sorry I haven't noticed the issue before now.  Did the change work?  I'll definitely roll it in, if so.

**Comment by evgeny-mezin-epam** [comment]
@kemenril Of course it worked! Highly recommend to merge that into master
