### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'groups'

### ISSUE THREAD

**Issue by W1LMS** [kemenril/iR-APRSISD#5]
Hello, I just performed a fresh install of Ubuntu on my VPS wanted to try our this iR to APRS. I initially started on 20.04 LTS and then 18.04 LTS. I get the same error on both attempts when running the daemon:

```
Traceback (most recent call last):
  File "./ir-aprsisd", line 118, in <module>
    (Call,SSNum) = re.search('(\w+)-(\d+)$',conf['APRS']['SSID']).groups()
AttributeError: 'NoneType' object has no attribute 'groups'
```

Was not sure was to what was causing this issue so figured I would start here.

Thanks for any help you can provide.

**Comment by W1LMS** [comment]
Disregard, I realize that specifying the SSID and IMEI is only for multiple devices and that I could specify it where the  CALLSIGN goes above.

**Comment by dd7rg** [comment]
Get this error as well, and it does not fix, if I do not use the multiple devices section. Furthermore if I look in the code, I thought only numeric SSID extensions are allowed (I'd like to use -IR, as this goes not over RF ...) but even if I specify -15 in the DEVICE section it flags above  errors ...
